import Image from 'next/image'

/**
 * Available basmilius weather icon names.
 * Icons are located in /public/icons/
 * @see https://github.com/basmilius/weather-icons
 */
export type IconName =
  | 'alert-avalanche-danger'
  | 'alert-falling-rocks'
  | 'barometer'
  | 'beanie'
  | 'celsius'
  | 'clear-day'
  | 'clear-night'
  | 'cloud-down'
  | 'cloud-up'
  | 'cloudy'
  | 'code-green'
  | 'code-orange'
  | 'code-red'
  | 'code-yellow'
  | 'compass'
  | 'drizzle'
  | 'dust'
  | 'dust-day'
  | 'dust-night'
  | 'dust-wind'
  | 'extreme'
  | 'extreme-day'
  | 'extreme-day-drizzle'
  | 'extreme-day-fog'
  | 'extreme-day-hail'
  | 'extreme-day-haze'
  | 'extreme-day-rain'
  | 'extreme-day-sleet'
  | 'extreme-day-smoke'
  | 'extreme-day-snow'
  | 'extreme-drizzle'
  | 'extreme-fog'
  | 'extreme-hail'
  | 'extreme-haze'
  | 'extreme-night'
  | 'extreme-night-drizzle'
  | 'extreme-night-fog'
  | 'extreme-night-hail'
  | 'extreme-night-haze'
  | 'extreme-night-rain'
  | 'extreme-night-sleet'
  | 'extreme-night-smoke'
  | 'extreme-night-snow'
  | 'extreme-rain'
  | 'extreme-sleet'
  | 'extreme-smoke'
  | 'extreme-snow'
  | 'fahrenheit'
  | 'falling-stars'
  | 'flag-gale-warning'
  | 'flag-hurricane-warning'
  | 'flag-small-craft-advisory'
  | 'flag-storm-warning'
  | 'fog'
  | 'fog-day'
  | 'fog-night'
  | 'freezing-drizzle'
  | 'glove'
  | 'hail'
  | 'haze'
  | 'haze-day'
  | 'haze-night'
  | 'horizon'
  | 'humidity'
  | 'hurricane'
  | 'lightning-bolt'
  | 'mist'
  | 'moon-first-quarter'
  | 'moon-full'
  | 'moon-last-quarter'
  | 'moon-new'
  | 'moon-waning-crescent'
  | 'moon-waning-gibbous'
  | 'moon-waxing-crescent'
  | 'moon-waxing-gibbous'
  | 'moonrise'
  | 'moonset'
  | 'not-available'
  | 'overcast'
  | 'overcast-day'
  | 'overcast-day-drizzle'
  | 'overcast-day-fog'
  | 'overcast-day-hail'
  | 'overcast-day-haze'
  | 'overcast-day-rain'
  | 'overcast-day-sleet'
  | 'overcast-day-smoke'
  | 'overcast-day-snow'
  | 'overcast-drizzle'
  | 'overcast-fog'
  | 'overcast-hail'
  | 'overcast-haze'
  | 'overcast-night'
  | 'overcast-night-drizzle'
  | 'overcast-night-fog'
  | 'overcast-night-hail'
  | 'overcast-night-haze'
  | 'overcast-night-rain'
  | 'overcast-night-sleet'
  | 'overcast-night-smoke'
  | 'overcast-night-snow'
  | 'overcast-rain'
  | 'overcast-sleet'
  | 'overcast-smoke'
  | 'overcast-snow'
  | 'partly-cloudy-day'
  | 'partly-cloudy-day-drizzle'
  | 'partly-cloudy-day-fog'
  | 'partly-cloudy-day-hail'
  | 'partly-cloudy-day-haze'
  | 'partly-cloudy-day-rain'
  | 'partly-cloudy-day-sleet'
  | 'partly-cloudy-day-smoke'
  | 'partly-cloudy-day-snow'
  | 'partly-cloudy-night'
  | 'partly-cloudy-night-drizzle'
  | 'partly-cloudy-night-fog'
  | 'partly-cloudy-night-hail'
  | 'partly-cloudy-night-haze'
  | 'partly-cloudy-night-rain'
  | 'partly-cloudy-night-sleet'
  | 'partly-cloudy-night-smoke'
  | 'partly-cloudy-night-snow'
  | 'partly-cloudy-rain'
  | 'partly-cloudy-snow'
  | 'pollen'
  | 'pollen-flower'
  | 'pollen-grass'
  | 'pollen-tree'
  | 'pressure-high'
  | 'pressure-high-alt'
  | 'pressure-low'
  | 'pressure-low-alt'
  | 'rain'
  | 'rainbow'
  | 'rainbow-clear'
  | 'raindrop'
  | 'raindrop-measure'
  | 'raindrops'
  | 'sleet'
  | 'smoke'
  | 'smoke-particles'
  | 'snow'
  | 'snowflake'
  | 'snowman'
  | 'solar-eclipse'
  | 'star'
  | 'starry-night'
  | 'sun-hot'
  | 'sunrise'
  | 'sunset'
  | 'thermometer'
  | 'thermometer-celsius'
  | 'thermometer-colder'
  | 'thermometer-fahrenheit'
  | 'thermometer-glass'
  | 'thermometer-glass-celsius'
  | 'thermometer-glass-fahrenheit'
  | 'thermometer-mercury'
  | 'thermometer-mercury-cold'
  | 'thermometer-moon'
  | 'thermometer-raindrop'
  | 'thermometer-snow'
  | 'thermometer-sun'
  | 'thermometer-warmer'
  | 'thermometer-water'
  | 'thunderstorms'
  | 'thunderstorms-day'
  | 'thunderstorms-day-extreme'
  | 'thunderstorms-day-extreme-rain'
  | 'thunderstorms-day-extreme-snow'
  | 'thunderstorms-day-overcast'
  | 'thunderstorms-day-overcast-rain'
  | 'thunderstorms-day-overcast-snow'
  | 'thunderstorms-day-rain'
  | 'thunderstorms-day-snow'
  | 'thunderstorms-extreme'
  | 'thunderstorms-extreme-rain'
  | 'thunderstorms-extreme-snow'
  | 'thunderstorms-night'
  | 'thunderstorms-night-extreme'
  | 'thunderstorms-night-extreme-rain'
  | 'thunderstorms-night-extreme-snow'
  | 'thunderstorms-night-overcast'
  | 'thunderstorms-night-overcast-rain'
  | 'thunderstorms-night-overcast-snow'
  | 'thunderstorms-night-rain'
  | 'thunderstorms-night-snow'
  | 'thunderstorms-overcast'
  | 'thunderstorms-overcast-rain'
  | 'thunderstorms-overcast-snow'
  | 'thunderstorms-rain'
  | 'thunderstorms-snow'
  | 'tide-high'
  | 'tide-low'
  | 'time-afternoon'
  | 'time-evening'
  | 'time-late-afternoon'
  | 'time-late-evening'
  | 'time-late-morning'
  | 'time-late-night'
  | 'time-morning'
  | 'time-night'
  | 'tornado'
  | 'umbrella'
  | 'umbrella-wind'
  | 'umbrella-wind-alt'
  | 'uv-index'
  | 'uv-index-1'
  | 'uv-index-10'
  | 'uv-index-11'
  | 'uv-index-2'
  | 'uv-index-3'
  | 'uv-index-4'
  | 'uv-index-5'
  | 'uv-index-6'
  | 'uv-index-7'
  | 'uv-index-8'
  | 'uv-index-9'
  | 'wind'
  | 'wind-alert'
  | 'wind-beaufort-0'
  | 'wind-beaufort-1'
  | 'wind-beaufort-10'
  | 'wind-beaufort-11'
  | 'wind-beaufort-12'
  | 'wind-beaufort-2'
  | 'wind-beaufort-3'
  | 'wind-beaufort-4'
  | 'wind-beaufort-5'
  | 'wind-beaufort-6'
  | 'wind-beaufort-7'
  | 'wind-beaufort-8'
  | 'wind-beaufort-9'
  | 'wind-offshore'
  | 'wind-onshore'
  | 'wind-snow'
  | 'windsock'
  | 'windsock-weak'

interface IconProps {
  icon: IconName
  alt?: string
}

/**
 * Icon component with accessibility support.
 * @param icon - The icon name (without extension)
 * @param alt - Alt text for accessibility. If empty string, image is decorative.
 */
export default function Icon({icon, alt}: Readonly<IconProps>) {
  return (
    <Image
      alt={alt ?? `weather icon: ${icon}`}
      src={`/icons/${icon}.svg`}
      height="150"
      width="150"
    />
  )
}
