name: Assertions

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  assertions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
