name: Assertions

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  assertions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependencies
        run: npm i

      - name: Copy .env
        run: cp .env.example .env

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
